version: "3.8"
services:
  go-server: 
    image: go
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: go-server
    ports:
      - 8080:8080
  nginx:
    image: reverse-proxy
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80
    
